version: "3.0"
services:
  postgres:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      TZ: "Europe/Paris"
    ports:
      - 5455:5432
